#fonts
font_size 11
font_family Iosevka NF Light
bold_font Iosevka NF Bold
italic_font Iosevka NF Light Obl
bold_italic_font Iosevka NF Bold Obl

#cursor
shell_integration no-cursor
cursor_shape beam
cursor_shape_unfocused beam
cursor_beam_thickness 1


#colors
cursor #ebdbb2
background #282828
foreground #ebdbb2
selection_background #3d4542
selection_foreground #ebdbb2

#those are like defaults
color0 #282828
color1 #cc241d
color2 #98971a
color3 #d79921
color4 #458588
color5 #b16286
color6 #689d6a
color7 #a89984

#and those are like the same but brighter
color8 #928374
color9 #fb4934
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2
